version: '2.4'
services:
  hello-svc:
    image: "servantscode/hello:latest"
    ports:
     - "8080:8080"
    mem_limit: 128m
    environment:
      ES_JAVA_OPTS: "-Xmx128m -Xms128m"
     
networks:
  default:
    external:
      name: docker-elk_elk
